version: 0.1
phases:
  pre_build:
    commands:
      - sh zipcode.sh
  build:
    commands:
      - aws cloudformation package --template-file cloudformation/root_template.yaml --s3-bucket eecs6895-project-src --output-template-file root_template_built.yaml
artifacts:
  files:
    - "**/*"