AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BasicLambdaRoleArn:
    Type: String

  SrcBucket:
    Type: String
    Default: eecs6895-fraud-detection-repo

  ProjectName:
    Type: String
    Default: fraud-detection


Resources:

  ApprovalRequest:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-approval-request
      Runtime: python3.8
      Code:
        S3Bucket: !Ref SrcBucket
        S3Key: src/approvalRequest/code.zip
      Role: !Ref BasicLambdaRoleArn
      Handler: handler.handler

  BatchWriter:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-batch-writer
      Runtime: python3.8
      Code:
        S3Bucket: !Ref SrcBucket
        S3Key: src/batchWriter/code.zip
      Role: !Ref BasicLambdaRoleArn
      Handler: handler.handler

  CheckResult:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-check-result
      Runtime: python3.8
      Code:
        S3Bucket: !Ref SrcBucket
        S3Key: src/checkResult/code.zip
      Role: !Ref BasicLambdaRoleArn
      Handler: handler.handler

  Classifier:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-classifier
      Runtime: python3.8
      Code:
        S3Bucket: !Ref SrcBucket
        S3Key: src/classifier/code.zip
      Role: !Ref BasicLambdaRoleArn
      Handler: handler.handler

  VerifyTransaction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-verify-transaction
      Runtime: python3.8
      Code:
        S3Bucket: !Ref SrcBucket
        S3Key: src/verifyTransaction/code.zip
      Role: !Ref BasicLambdaRoleArn
      Handler: handler.handler