AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VpcID:
    Type: String
  RouteTableID:
    Type: String
  SecurityGroupID:
    Type: String
  PrivateSubnetA:
    Type: String
  PrivateSubnetB:
    Type: String

  ProjectName:
    Type: String
    Default: fraud-detection

Resources:
  TransactionDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-transaction-table
      AttributeDefinitions:
        - AttributeName: "user_id"
          AttributeType: "S"
        - AttributeName: "transaction_id"
          AttributeType: "S"

      KeySchema:
        - AttributeName: "user_id"
          KeyType: "HASH"
        - AttributeName: "transaction_id"
          KeyType: "RANGE"

      BillingMode: "PAY_PER_REQUEST"

  DBEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: !GetAtt TransactionDB.Arn
            Principal: "*"
      RouteTableIds:
        - !Ref RouteTableID
      ServiceName: com.amazonaws.us-east-1.dynamodb
      VpcId: !Ref VpcID

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: "redis-subnet-group"
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      Description: "subnet group for the redis cluster"

  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      ClusterName: "redis-cache-cluster"
      Engine: "redis"
      NumCacheNodes: 1
      CacheNodeType: "cache.t3.small" # $0.8 per day
      VpcSecurityGroupIds:
        - !Ref SecurityGroupID
      CacheSubnetGroupName: !Ref RedisSubnetGroup
